name: Node.js CI

on:
  # 手动触发
  workflow_dispatch:
  # 定时器 github服务器时间比北京时间晚8小时 定时早上6点执行
  # schedule: 
    # - cron: '0 20,22 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

     strategy:
      matrix:
        node-version: [12.7.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: npm install
      run: npm install
    
    - name: npm start
      run: npm start
      env:
          appId: ${{ secrets.APPID }}
          appKey: ${{ secrets.APPKEY }}
